
mutation groupTypeDelete($id: UUID!, $lastchange: DateTime!) {
  result: groupTypeDelete(groupType: {id: $id, lastchange: $lastchange}) {
    ...Error
  }
}

fragment Error on GroupTypeGQLModelDeleteError {
  __typename
  failed
  input
  Entity {
    ...GroupTypeModel
  }
  msg
}

fragment GroupTypeModel on GroupTypeGQLModel {
  __typename
  id
  lastchange
  name
  nameEn
}