mutation roleDelete($id: UUID!, $lastchange: DateTime!) {
  result: roleDelete(
    role: {id: $id, lastchange: $lastchange}
  ) {
    ...Error
  }
}

fragment Error on RoleGQLModelDeleteError {
  __typename
  failed
  input
  msg
  Entity {
    ...Role
  }
}


fragment Role on RoleGQLModel {
  __typename
  id
  roletype { id name }
  
  lastchange
  created
  createdby {
    id
    email
  }
  changedby {
    id
    email
  }
}