mutation RoleTypeInsert($id: UUID, $name: String!, $category_id: UUID!) {
  result: roleTypeInsert(roleType: {id: $id, name: $name, categoryId: $category_id}) {
    ...RoleType
    ...Error
  }
}

fragment Error on InsertError {
  __typename
  failed
  input
  msg
}

fragment RoleType on RoleTypeGQLModel {
	__typename
  id
  lastchange
  name
  nameEn
  
  created
  createdby { id email }
  changedby { id email }
}

