mutation($id: UUID!, $lastchange: DateTime!, $name: String!, $name_en: String) {
  result: groupCategoryUpdate(groupCategory: {id: $id, lastchange: $lastchange, name: $name, nameEn: $name_en}) {
    ...GroupCategoryModel
    ...Error
  }
}

fragment Error on GroupCategoryGQLModelUpdateError {
  __typename
  failed
  input
  Entity {
    ...GroupCategoryModel
  }
  msg
}

fragment GroupCategoryModel on GroupCategoryGQLModel {
  __typename
    id
    lastchange
    name
    nameEn

    rbacobject { id }
}