mutation roleTypeListAddRole($roletypelist_id: UUID!, $roletype_id: UUID!) {
  result: roleTypeListAddRole(
    entity: {typeId: $roletype_id, id: $roletypelist_id}
  ) {
    ...RoleTypeList
    ...Error
  }
}

fragment Error on InsertError {
  __typename
  failed
  msg
  input
}

fragment RoleTypeList on RoleTypeListGQLModel {
  __typename
  id
  lastchange
}