mutation($id: UUID!, $grouptype_id: UUID!, $mastergroup_id: UUID, $name: String!, $name_en: String) {
  result: groupInsert(group: {id: $id, name: $name, nameEn: $name_en, grouptypeId: $grouptype_id, mastergroupId: $mastergroup_id}) {
    ...GroupModel
    ...Error
  }
}

fragment Error on InsertError {
  __typename
  failed
  input
  msg
}

fragment GroupModel on GroupGQLModel {
  __typename
  id
  lastchange
  name
  nameEn
  rbacobject {
    id
  }
  subgroups {
    id
    name
  }

}