query ($id: UUID!) {
  result: groupById(id: $id) {
    ...GroupModel
    ...Coverage
  }
}

fragment GroupModel on GroupGQLModel {
  __typename
  id
  lastchange
  name
  nameEn
  rbacobject {
    id
  }
  subgroups {
    id
    name
  }

}

fragment Coverage on GroupGQLModel {
  Subgroups {
    pageInfo {
        after
        before
        first
        last
        hasNextPage
    }    
    edges {
        cursor
        node {
            id
            name
        }
    }
  }
  Memberships {
    edges {
        cursor
    }
  }
}