query ($limit: Int, $skip: Int, $where: UserInputWhereFilter) {
  result: userPage(limit: $limit, skip: $skip, where: $where) {
    __typename
    ...User
  }
}

fragment User on UserGQLModel {
  id
  lastchange
  name
  surname
  email
  isThisMe
  rolesOn {
    id
    user {
      email
    }
    roletype {
      name
    }
  }
  memberOf {
    name
  }
  id
}